services:

  # ============================================
  # üìã ORDER SERVICE
  # ============================================
  order-service:
    build: .
    container_name: order-service
    depends_on:
      order-postgres:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GATEWAY_SECRET: ${GATEWAY_SECRET}
      SERVICE_SECRET: ${SERVICE_SECRET}
    restart: always
    networks:
      - brokerx-network

  order-postgres:
    image: postgres:17
    container_name: order-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - brokerx-network

  order-redis:
    image: redis:7.4
    container_name: order-redis
    restart: always
    expose:
      - "6379"
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no"
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - brokerx-network


# ============================================
# üåê NETWORKS
# ============================================

networks:
  brokerx-network:
    external: true
    name: brokerx-network

# ============================================
# üíæ VOLUMES
# ============================================

volumes:
  order_postgres_data:
    name: order_postgres_data